export const navLinks = [
  { label: "Home", href: "#home" },
  { label: "About", href: "#about" },
  { label: "Skills", href: "#skills" },
  { label: "Projects", href: "#projects" },
  { label: "Experience", href: "#experience" },
  { label: "Blog", href: "#blog" },
  { label: "Contact", href: "#contact" },
];

export const skillsByCategory = {
  Frontend: ["React.js", "JavaScript", "HTML5", "CSS3", "Tailwind CSS"],
  Backend: ["Node.js", "Express.js", "REST APIs", "JWT Authentication"],
  "Database & Cloud": ["MongoDB", "MySQL", "Firebase"],
  Tools: ["Git", "GitHub", "Postman", "VS Code", "Figma"],
  "AI / Data": ["Python", "Machine Learning Basics", "Data Analysis", "Power BI"],
};

export const services = [
  {
    title: "Full-Stack Web Applications",
    tech: "React, Node.js, MongoDB",
    description:
      "Complete web platforms with frontend, backend, authentication, dashboards, and database integration.",
  },
  {
    title: "Admin Dashboards",
    tech: "React, Tailwind, REST APIs",
    description:
      "Modern dashboard panels with analytics, tables, management tools, and responsive layouts.",
  },
  {
    title: "AI-Integrated Applications",
    tech: "Python, APIs, ML basics",
    description:
      "Smart application flows with automation, recommendation logic, and intelligent features.",
  },
  {
    title: "Portfolio & Business Websites",
    tech: "React, Tailwind, SEO",
    description:
      "Professional websites for personal brands, services, products, and businesses.",
  },
];

export const projects = [
  {
    title: "Mathaka - Live in Concert",
    category: "Full Stack",
    type: "Client Event Booking Platform",
    status: "Live",
    stack: ["Event Booking", "Admin Dashboard", "Client Project"],
    imgUrl: "/img/mathaka.png",
    github: "",
    live: "https://www.dimuthuevents.com",
    description:
      "Production event booking website delivered for a client, including ticket discovery, booking flows, and an administration dashboard.",
    features: ["Event ticket booking", "Admin dashboard", "Live client deployment"],
  },
  {
    title: "Cypex CloudBook",
    category: "DevOps",
    type: "Automated Content Platform",
    status: "Live",
    stack: ["Scheduled Publishing", "GitHub Automation", "Auto Deployment"],
    imgUrl: "/img/cloudbook.png",
    github: "",
    live: "https://www.cypexcloudbook.com",
    description:
      "Content platform that automatically generates scheduled blog posts, publishes through GitHub, and deploys new content automatically.",
    features: ["Automated posts", "Scheduled publishing", "Deployment workflow"],
  },
  {
    title: "PromptEarn",
    category: "DevOps",
    type: "Automated AI Content Platform",
    status: "Live",
    stack: ["Content Automation", "GitHub Workflow", "Scheduled Deploys"],
    imgUrl: "/img/promptearn.png",
    github: "",
    live: "https://www.promptearnhqxyz.xyz",
    description:
      "AI-focused blog platform with scheduled content generation, automatic GitHub publishing, and continuous deployment.",
    features: ["AI content topics", "Automated publishing", "Live scheduled updates"],
  },
  {
    title: "Mood Salon Dubai",
    category: "Frontend",
    type: "Business Website",
    status: "Live",
    stack: ["Salon Website", "Service Showcase", "WhatsApp Booking"],
    imgUrl: "/img/mood-salon.png",
    github: "https://github.com/Yasirunk9612/mood-salon",
    live: "https://mood-salon-puce.vercel.app",
    description:
      "Premium beauty lounge website for Mood Salon Dubai with service discovery, gallery, reviews, and direct booking calls to action.",
    features: ["Service packages", "Booking CTA", "Luxury responsive design"],
  },
  {
    title: "Vegetable Shop POS",
    category: "Desktop",
    type: "Windows POS Application",
    status: "Live",
    stack: [".NET 8", "WPF", "SQLite", "Material Design"],
    imgUrl: "/img/vegetable-pos.png",
    github: "",
    live: "https://yasirunk9612.github.io/site-wegi-pos/",
    description:
      "Professional POS solution for wholesale vegetable trading, with a Windows download portal and fast checkout-focused workflows.",
    features: ["Sales flow", "Inventory handling", "Windows download"],
  },
  {
    title: "Restaurant POS",
    category: "Desktop",
    type: "Windows POS Application",
    status: "Live",
    stack: ["Electron", "Vite", "React", "Prisma", "SQLite"],
    imgUrl: "/img/restaurant-pos.png",
    github: "",
    live: "https://yasirunk9612.github.io/restaurant-POS-web/",
    description:
      "Modern desktop restaurant point-of-sale product for ordering, dining and takeaway workflows, and clean receipt handling.",
    features: ["Order entry", "POS dashboard", "Windows download"],
  },
  {
    title: "DK Motors",
    category: "Frontend",
    type: "Automotive Business Website",
    status: "Live",
    stack: ["Vehicle Showcase", "Responsive UI", "Lead Generation"],
    imgUrl: "/img/dk-motors.png",
    github: "https://github.com/Yasirunk9612/car-shop",
    live: "https://dk-motors-dusky.vercel.app",
    description:
      "Automotive brand website presenting Japanese performance cars and motorcycles with service exploration and quote conversion flows.",
    features: ["Vehicle branding", "Services showcase", "Quote CTA"],
  },
  {
    title: "Anime Book Selling Platform",
    category: "Full Stack",
    type: "Web Application",
    status: "Completed",
    stack: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"],
    imgUrl: "/img/anime.png",
    github: "https://github.com/Yasirunk9612/Anime-Book-Selling-website",
    live: "#",
    description:
      "Full-stack e-commerce platform with admin panel, authentication, catalog, shopping cart, and order management.",
    features: ["User authentication", "Book catalog", "Cart and orders"],
  },
  {
    title: "PS Portfolio - University Project",
    category: "Frontend",
    type: "Web Application",
    status: "Completed",
    stack: ["HTML", "CSS", "JavaScript"],
    imgUrl: "/img/ps.png",
    github: "https://github.com/Yasirunk9612/PS_Portfolio",
    live: "https://ps-portfolio-uni.vercel.app",
    description:
      "Professional portfolio website with responsive design and modern interactions for academic showcase.",
    features: ["Responsive layout", "Project showcase", "Clean UI"],
  },
  {
    title: "Pizza Shop",
    category: "Full Stack",
    type: "Web Application",
    status: "Completed",
    stack: ["Next.js", "React", "JavaScript", "Tailwind", "Node.js", "MongoDB", "Express.js"],
    imgUrl: "/img/pizza.png",
    github: "#",
    live: "https://pazz-pizza.vercel.app",
    description:
      "Modern pizza ordering platform built with Next.js and full-stack architecture.",
    features: ["Menu display", "Ordering flow", "Responsive pages"],
  },
  {
    title: "Cypex Technologies Website",
    category: "Frontend",
    type: "Web Application",
    status: "Completed",
    stack: ["Next.js", "React", "JavaScript", "CSS"],
    imgUrl: "/img/cypex.png",
    github: "#",
    live: "https://cypex-website.vercel.app",
    description: "Official company website for Cypex Technologies, presenting its services and technology-focused brand.",
    features: ["Company identity", "Service pages", "Modern responsive UX"],
  },
  {
    title: "Travel Website - Next.js",
    category: "Frontend",
    type: "Web Application",
    status: "Completed",
    stack: ["Next.js", "React", "JavaScript", "CSS"],
    imgUrl: "/img/T1.png",
    github: "https://github.com/Yasirunk9612/Travel-Website",
    live: "#",
    description: "Travel platform concept with destination browsing and modern section layouts.",
    features: ["Destination cards", "Responsive UI", "Modern structure"],
  },
  {
    title: "TechRepair Shop - Desktop Management System",
    category: "Desktop",
    type: "Management System",
    status: "Completed",
    stack: ["Java", "Swing", "MySQL"],
    imgUrl: "/img/techRep.png",
    github: "",
    live: "#",
    description: "Desktop management software for orders, suppliers, inventory, employees, and reports.",
    features: ["Order management", "Inventory control", "Reporting"],
  },
  {
    title: "Travel Companion App - Android Project",
    category: "Mobile",
    type: "Mobile Application",
    status: "Completed",
    stack: ["Java", "Firebase"],
    imgUrl: "/img/travelapp.jpeg",
    github: "",
    live: "#",
    description: "Mobile travel assistant for itinerary handling, weather, and local recommendations.",
    features: ["Itinerary planning", "Weather updates", "Recommendations"],
  },
  {
    title: "CI/CD Application",
    category: "DevOps",
    type: "Application",
    status: "Completed",
    stack: ["JavaScript", "Docker", "GitHub Actions", "Node.js"],
    imgUrl: "/img/cicd-project.svg",
    github: "https://github.com/Yasirunk9612/ci-cd-app",
    live: "#",
    description: "CI/CD pipeline implementation showcasing automated testing and deployment workflows.",
    features: ["CI pipelines", "Build automation", "Deploy workflow"],
  },
  {
    title: "Event Management System",
    category: "Frontend",
    type: "Web Application",
    status: "Completed",
    stack: ["JavaScript", "HTML", "CSS", "Local Storage"],
    imgUrl: "/img/event-system.svg",
    github: "https://github.com/Yasirunk9612/event",
    live: "#",
    description: "Event manager with registration and administrative controls using modern JS.",
    features: ["Event listing", "Registrations", "Simple admin flow"],
  },
];

export const featuredWork = [
  {
    title: "Mathaka - Live in Concert",
    badge: "Client Project",
    problem: "A live concert needed a polished ticket booking presence and manageable event operations.",
    impact: "Delivered a live event booking website with an administration dashboard for client-side event control.",
    features: ["Ticket booking", "Admin dashboard", "Production release"],
    stack: ["Event Platform", "Admin Tools", "Live Deployment"],
    imgUrl: "/img/mathaka.png",
    github: "",
    live: "https://www.dimuthuevents.com",
  },
  {
    title: "Cypex CloudBook",
    badge: "Publishing Automation",
    problem: "Content sites need consistent publishing without manually deploying every scheduled article.",
    impact: "Automated scheduled blog creation, GitHub publication, and deployment updates in one live product.",
    features: ["Scheduled posts", "GitHub automation", "Automatic deployment"],
    stack: ["Automation", "Content Platform", "CI/CD"],
    imgUrl: "/img/cloudbook.png",
    github: "",
    live: "https://www.cypexcloudbook.com",
  },
  {
    title: "PromptEarn",
    badge: "AI Content Platform",
    problem: "AI learners need continuously published practical guidance delivered through a reliable content workflow.",
    impact: "Built an automated blog platform that generates and publishes scheduled AI-focused posts live.",
    features: ["Content generation", "Scheduled publishing", "Continuous deployment"],
    stack: ["AI Topics", "Automation", "GitHub Deploy"],
    imgUrl: "/img/promptearn.png",
    github: "",
    live: "https://www.promptearnhqxyz.xyz",
  },
];
